name: wow_gold_buy_v3
description: Gold Shop In Azeroth.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  toggle_switch: ^2.3.0
  cupertino_icons: ^1.0.8
  email_validator: ^3.0.0
  win32: ^5.14.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
